// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivnczarwkkeyncwrovio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2bmN6YXJ3a2tleW5jd3JvdmlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4NzQwMjcsImV4cCI6MjA4ODQ1MDAyN30.0gBilYN_02R88rYio1OWTuRAIoYk3ydDP6qe_nJzlYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});